import assert from 'node:assert/strict';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { pathToFileURL, fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { createServer } from 'node:http';

const root = fileURLToPath(new URL('../../', import.meta.url));
const campaign = resolve(process.argv[2]), output = resolve(process.argv[3]);
const measure = process.env.VBP_COMPONENT_MEASURE === '1';
const profile = process.env.VBP_COMPONENT_PROFILE === '1';
const rich = process.env.VBP_COMPONENT_RICH === '1';
assert(!profile || measure, 'CPU sampling requires the measured component boundary');
assert(!rich || !measure, 'Rich acceptance is separate from the frozen timing cohort');
const sha = b => createHash('sha256').update(b).digest('hex');
const json = async path => JSON.parse(await readFile(path));
const sourceIdentity = await json(resolve(campaign, 'identity.json'));
for (const f of sourceIdentity.sourceFiles) assert.equal(
  sha(await readFile(resolve(campaign, f.path))), f.sha256, `frozen source changed: ${f.path}`);
const firRoot = resolve(campaign, 'fir');
const { verifyBrowserPackage } = await import(pathToFileURL(resolve(firRoot, 'verified-package.mjs')));
const { componentPackagePolicy } = await import(pathToFileURL(resolve(firRoot, 'component-package-policy.mjs')));
const verified = verifyBrowserPackage(firRoot, componentPackagePolicy);
assert.equal(sha(await readFile(resolve(firRoot, 'BUILD.json'))), sourceIdentity.firBuildSha256);
const virRoot = resolve(root, '.lake/packages/lean_vir');
const frozenVir = resolve(campaign, 'source/.lake/packages/lean_vir');
const sdkRoot = resolve(root, '.lake/build/vir/sdk');
const sdk = await json(resolve(sdkRoot, 'lean-vir-artifact.json'));
assert.equal(sdk.gitCommit, '36d26bc224f0c2a52cd586587b2c3e1b1ade70d6');
assert.equal(sdk.gitDirty, false);
assert.equal(sdk.leanToolchain, 'leanprover/lean4:v4.34.0-rc2');
for (const f of sdk.files) assert.equal(sha(await readFile(resolve(sdkRoot, f.path))), f.sha256, f.path);
const lock = await json(resolve(frozenVir, 'package-lock.json'));
for (const p of verified.build.externalProviders.react) {
  assert.equal(lock.packages[`node_modules/${p.name}`].version, p.version);
  assert.equal(lock.packages[`node_modules/${p.name}`].integrity, p.integrity);
  assert.equal((await json(resolve(virRoot, 'node_modules', p.name, 'package.json'))).version, p.version);
}
for (const f of verified.build.externalProviders.sources) assert.equal(
  sha(await readFile(resolve(frozenVir, f.path))), f.sha256, f.path);
const descriptorPath = resolve(campaign, 'source/.lake/build/vir/module-sets/VersoBlueprintVirTests/NativeSession.irpkg-set.json');
const descriptor = await json(descriptorPath);
const packages = await Promise.all(descriptor.packages.map(p => readFile(resolve(dirname(descriptorPath), p.path))));
const inputs = [...await json(resolve(firRoot, 'documents.json')), ...await Promise.all(
  ['before','after'].map(name => readFile(resolve(root, '../../_out/browser-pr188/widget-baseline-inputs', `${name}.document.json`), 'utf8')))];
// Reuse bytes generated by Lean in the earlier renderer acceptance, not a JS schema.
const richInputPath = resolve(root, '../../_out/browser-pr188/json-renderer-acceptance-v2/inputs.json');
if (rich) {
  const fixtures = await json(richInputPath);
  assert.equal(fixtures.length, 2);
  assert(fixtures.every(input => typeof input === 'string'));
  inputs.push(...fixtures);
}
await mkdir(output, { recursive: false });
await writeFile(resolve(output, 'identity.json'), JSON.stringify({
  sourceIdentity: sourceIdentity.sourceIdentity, firBuildSha256: sourceIdentity.firBuildSha256,
  firWasmSha256: verified.build.wasm.sha256, sdkManifestSha256: sha(await readFile(resolve(sdkRoot,'lean-vir-artifact.json'))),
  controlPackages: packages.map(sha), inputs: inputs.map(input => ({ bytes: Buffer.byteLength(input), sha256: sha(input) })),
  noTimings: !measure, reactMode: { ssr: 'production', browser: measure ? 'production' : 'development' },
  root, virCommit: sdk.gitCommit, toolchain: sdk.leanToolchain,
  cpuSampling: profile ? 'CDP 1ms; attribution only' : false,
  firPackage: firRoot,
  ...(rich ? { richInputCapture: richInputPath, richInputCaptureSha256: sha(await readFile(richInputPath)) } : {}),
}, null, 2));
const { build } = await import(pathToFileURL(resolve(virRoot, 'node_modules/esbuild/lib/main.js')));
const entry = resolve(root, 'tests/vir_preview/component_campaign_entry.mjs');
const options = { entryPoints: [entry], bundle: true, write: false,
  nodePaths: [resolve(virRoot, 'node_modules')], define: { 'process.env.NODE_ENV': '"production"' },
  alias: { 'lean-vir': resolve(sdkRoot, 'js/vir-runtime.js'),
    'lean-vir/host-bindings': resolve(sdkRoot, 'js/vir-host-bindings.js'),
    '@component-react': resolve(frozenVir, 'web/src/vir-react-host-bindings.js'),
    '@component-collections': resolve(frozenVir, 'web/src/host/vir-js-collection-bindings.js'),
    '@component-values': resolve(frozenVir, 'web/src/host/vir-js-value-bindings.js'),
    '@component-events': resolve(frozenVir, 'web/src/host/vir-dom-host-bindings.js'),
    '@component-bootstrap': resolve(firRoot, 'component-session-bootstrap.mjs') } };
let ssr;
if (!measure) {
  const ssrBundle = await build({ ...options, platform: 'node', format: 'esm',
    banner: { js: 'import { createRequire } from "node:module"; const require = createRequire(import.meta.url);' } });
  await writeFile(resolve(output, 'ssr.mjs'), ssrBundle.outputFiles[0].contents);
  const { runSsr } = await import(pathToFileURL(resolve(output, 'ssr.mjs')));
  ssr = await runSsr({ fir: { module: verified.module,
    manifest: await json(resolve(firRoot,'component.wasm.json')), hostBoundary: await json(resolve(firRoot,'host-boundary.json')),
    callbackBoundary: await json(resolve(firRoot,'callback-boundary.json')) }, vir: {
      wasmBytes: await readFile(resolve(sdkRoot, 'wasm/vir-upstream.wasm')), irPackageSet: packages } }, inputs);
  await writeFile(resolve(output, 'ssr.json'), JSON.stringify(ssr, null, 2));
} else {
  const prior = await json(resolve(root, '../../_out/browser-pr188/component-campaign-20260916-01/result.json'));
  const priorIdentity = await json(resolve(root, '../../_out/browser-pr188/component-campaign-20260916-01/identity.json'));
  assert.equal(prior.ssr.exactSsrEquality, true);
  assert.equal(prior.browser.exactDomEquality, true);
  assert.equal(priorIdentity.sourceIdentity, sourceIdentity.sourceIdentity);
  assert.equal(priorIdentity.firBuildSha256, sourceIdentity.firBuildSha256);
  assert.deepEqual(priorIdentity.controlPackages, packages.map(sha));
  assert.deepEqual(priorIdentity.inputs, inputs.map(input => ({ bytes: Buffer.byteLength(input), sha256: sha(input) })));
}
const wasmBytes = await readFile(resolve(sdkRoot, 'wasm/vir-upstream.wasm'));
// React.act is a development acceptance API; browser uses development React.
const browserBundle = await build({ ...options,
  entryPoints: [measure ? resolve(root,'tests/vir_preview/component_campaign_phase_entry.mjs') : entry],
  define: { 'process.env.NODE_ENV': measure ? '"production"' : '"development"',
    'process.env.VBP_COMPONENT_MEASURE': measure ? '"1"' : '"0"',
    'process.env.VBP_COMPONENT_RICH': rich ? '"1"' : '"0"',
    'process.env.VBP_COMPONENT_PROFILE': profile ? '"1"' : '"0"' },
  ...(profile ? { outfile: resolve(output,'probe.js'), sourcemap: 'external' } : {}),
  platform: 'browser', format: 'iife', target: 'chrome120' });
const browserCode = profile ? browserBundle.outputFiles.find(f => f.path.endsWith('/probe.js')).contents
  : browserBundle.outputFiles[0].contents;
if (profile) for (const file of browserBundle.outputFiles) await writeFile(file.path,file.contents);
const assets = new Map([
  ['/', ['text/html', '<!doctype html><meta charset="utf-8"><div id="app"></div><script src="/probe.js"></script>']],
  ['/probe.js', ['text/javascript', browserCode]],
  ['/component.wasm', ['application/wasm', await readFile(resolve(firRoot,'component.wasm'))]],
  ['/runtime.wasm', ['application/wasm', wasmBytes]],
  ['/inputs.json', ['application/json', JSON.stringify(inputs)]],
  ['/control.irpkg-set.json', ['application/json', JSON.stringify({ ...descriptor,
    packages: descriptor.packages.map((p,i) => ({ ...p, path: `control-${i}.irpkg` })) })]],
]);
for (const file of ['component.wasm.json','host-boundary.json','callback-boundary.json'])
  assets.set(`/${file}`, ['application/json', await readFile(resolve(firRoot,file))]);
packages.forEach((bytes,i) => assets.set(`/control-${i}.irpkg`, ['application/octet-stream', bytes]));
const { launchChromium, openChromiumPage, navigate, evaluate } = await import(pathToFileURL(resolve(virRoot,'tests/browser/harness.mjs')));
let server, chrome, cdp, deadline;
try {
  server = createServer(async (req,res) => {
    if (profile && ['/profile/start','/profile/stop'].includes(req.url)) {
      try {
        if (req.url === '/profile/start') {
          await cdp.send('Performance.enable');
          const stamp = async () => (await cdp.send('Performance.getMetrics')).metrics.find(m=>m.name==='Timestamp').value*1000;
          const before = await stamp(), browserNow = await evaluate(cdp,'performance.now()'), after = await stamp();
          const clock = {before,browserNow,after,offsetMs:(before+after)/2-browserNow,uncertaintyMs:(after-before)/2};
          assert(clock.uncertaintyMs<5,'profile clock too imprecise');
          await writeFile(resolve(output,'profile-clock.json'),JSON.stringify(clock,null,2));
          await cdp.send('Profiler.enable');
          await cdp.send('Profiler.setSamplingInterval',{interval:1000});
          await cdp.send('Profiler.start');
        } else {
          const {profile: capture} = await cdp.send('Profiler.stop');
          await writeFile(resolve(output,'browser.cpuprofile'),JSON.stringify(capture));
        }
        res.writeHead(200);res.end('ok');
      } catch(error) {res.writeHead(500);res.end(String(error));}
      return;
    }
    const asset = assets.get(req.url);
    res.writeHead(asset ? 200 : 404, { 'content-type': asset?.[0] ?? 'text/plain' }); res.end(asset?.[1] ?? 'not found'); });
  await new Promise(done => server.listen(0,'127.0.0.1',done));
  chrome = await launchChromium(); cdp = await openChromiumPage(chrome);
  await navigate(cdp, `http://127.0.0.1:${server.address().port}/`);
  const browser = await Promise.race([evaluate(cdp,'globalThis.componentCampaign'), new Promise((_,reject) => {
    deadline = setTimeout(() => reject(Error('matched component acceptance timeout')), 240000); })]);
  await writeFile(resolve(output,'browser.json'), JSON.stringify(browser,null,2));
  assert.equal(browser?.ok,true,JSON.stringify(browser));
  const result = { ...(ssr ? {ssr} : {}), browser: browser.value, noTimings: !measure };
  await writeFile(resolve(output,'result.json'), JSON.stringify(result,null,2));
  console.log(JSON.stringify(result,null,2));
} finally {
  clearTimeout(deadline); await cdp?.close(); await chrome?.close();
  if(server?.listening) await new Promise(done => server.close(done));
}
