/-
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Emilio J. Gallego Arias
-/

import VersoBlueprintTests.BlueprintImportedContributions.Diamond
import VersoBlueprintTests.BlueprintImportedContributions.ObserveAttachment
import VersoBlueprintTests.BlueprintImportedContributions.Attachments
import VersoBlueprintTests.BlueprintImportedContributions.Filled
import VersoBlueprintTests.BlueprintImportedContributions.Render
import VersoBlueprintTests.BlueprintImportedContributions.KindForward
import VersoBlueprintTests.BlueprintImportedContributions.KindReverse
import VersoBlueprintTests.BlueprintImportedContributions.AtomicFailure
import VersoBlueprintTests.BlueprintImportedContributions.LateRender
import VersoBlueprintTests.BlueprintImportedContributions.DependencyAuthority
import VersoBlueprintTests.BlueprintImportedContributions.Coverage
import VersoBlueprintTests.BlueprintImportedContributions.LiterateRender
import VersoBlueprintTests.BlueprintImportedContributions.LiterateKindForward
import VersoBlueprintTests.BlueprintImportedContributions.LiterateKindReverse
import VersoBlueprintTests.BlueprintImportedContributions.SnapshotIsolation
