/-
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Emilio J. Gallego Arias
-/

-- Generated by scripts/bindings/generate-lean-bindings.mjs. Do not edit.

module

public import VersoBlueprintVirTests.NativeSession.UpstreamJson.Types

public section

namespace Lean.Vir.JsonValue

namespace Internal

/--
Generated binding for reviewed VIR protocol `json-value.check`.

Explicitly validates the complete ordinary-value graph before copying it into Lean; rejects unsupported shapes, non-safe-integer numbers and reserved reference objects.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-json-value-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; result lean-owned/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "jsonValue.check"]
private opaque check
    (value : @& Js.Any) :
    Lean.Vir.RuntimeM (Except String Unit)

/--
Generated binding for reviewed VIR protocol `json-value.inspect`.

Copies a validated JSON node into the existing structural object ABI while child values remain exact JS resources. Used synchronously after the whole-graph check.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-json-value-v1` (bridge-handle retention): receiver none; value js-resource/borrowed/call; result lean-owned/value.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "jsonValue.inspect"]
private opaque inspect
    (value : @& Js.Any) :
    Lean.Vir.RuntimeM (View)

/--
Generated binding for reviewed VIR protocol `json-value.build`.

Explicitly constructs one ordinary JSON node from checked Lean values and already converted JS children; no wire stringify or implicit binding conversion.

Binding contract: `generation.protocolOperations`.

ABI profile `vir-json-value-v1` (bridge-handle retention): receiver none; value lean-owned/borrowed/call; result js-resource/owned.

This declaration is generated; edit the binding configuration.
-/
@[vir_js_explicit_conversion "jsonValue.build"]
private opaque build
    (value : @& View) :
    Lean.Vir.RuntimeM (Js.Any)

end Internal

end Lean.Vir.JsonValue
