/-
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Emilio J. Gallego Arias
-/

module

import VersoBlueprintVir
import VersoBlueprintVirTests.Preview.Document
meta import VersoBlueprintVir
meta import VersoBlueprintVirTests.Preview.Document

namespace VersoBlueprintVirTests.VirPreview

open Verso
open Verso.Doc
open VersoBlueprint.Experimental.VirPreview

/-- The real Manual part generated by the renderer fixture's top-level `#doc`. -/
private def source : Part Genre.Manual :=
  %doc VersoBlueprintVirTests.Preview.Document

private def paragraph (text : String) : Block Genre.Manual :=
  .para #[.text text]

private def document (version : Nat) (content : Array String) : Document := {
  version
  correlationId := s!"vbp-preview-{version}"
  cursorToken := s!"{version}:0"
  document := .mk #[.text "VBP preview"] "VBP preview" none
    (content.map paragraph) #[]
}

private def beforeInsertion : Document :=
  document 1 #["A", "B", "C"]

private def afterInsertion : Document :=
  document 2 #["A", "X", "B", "C"]

private def afterMove : Document :=
  document 3 #["C", "A", "B"]

private def realDocument : Document := {
  version := 7
  correlationId := "vbp-preview-fixture-7"
  cursorToken := "27:4"
  document := source
}

private def sample : Preview :=
  .ready realDocument

private def statusSamples : Array Preview := #[
  .loading "Preparing the cursor document",
  .unavailable "No Blueprint document at the cursor",
  sample,
  .error "Document preparation failed"
]

#guard match Preview.decode sample.encode with
  | .ok actual => actual == sample
  | .error _ => false

private def timing : ServerTiming := {
  snapshotWaitNanos := 266100000
  checkedWaitNanos := 8600000
  evaluationNanos := 700000
}

private def timedSample : Preview :=
  .ready { realDocument with serverTiming? := some timing }

#guard timing.preparationNanos == 275400000
#guard !Session.Options.initial.highlightChanges
#guard !({ Session.Options.initial with debug := true } : Session.Options).highlightChanges

#guard Session.formatMs (timing.preparationNanos.toFloat / 1000000.0) == "275.4"

#guard match Preview.decode timedSample.encode with
  | .ok actual => actual == timedSample
  | .error _ => false

-- A normal producer can omit the optional wire field altogether.
#guard match Lean.toJson realDocument with
  | .obj fields =>
    match Lean.fromJson? (Lean.Json.mkObj (fields.toList.filter (·.1 != "serverTiming"))) with
    | .ok (actual : Document) => actual == realDocument
    | .error _ => false
  | _ => false

#guard statusSamples.all fun preview =>
  match Preview.decode preview.encode with
  | .ok actual => actual == preview
  | .error _ => false

#guard source.titleString == "VBP Verso renderer fixture"
#guard source.content.isEmpty
#guard source.subParts.size == 1
#guard source.subParts[0]!.content.size >= 12
#guard source.subParts[0]!.subParts.size == 1
#guard (Renderer.renderBlockIds realDocument).size >= 12
#guard Renderer.changedBlockIds beforeInsertion beforeInsertion |>.isEmpty
#guard Renderer.changedBlockIds beforeInsertion afterInsertion == #["part-root-block-1"]
#guard Renderer.changedBlockIdsAndCount (some beforeInsertion) afterInsertion ==
  (#["part-root-block-1"], 5)
#guard Renderer.changedBlockIds beforeInsertion afterMove |>.isEmpty

end VersoBlueprintVirTests.VirPreview
